### ISSUE TITLE
Valarray vs. vector

### ISSUE THREAD

**Issue by Lecrapouille** [martinjrobins/Aboria#17]
Hi, I just discovered your project which seems very interesting. Concerning the internal data storage for variables, have you tried http://en.cppreference.com/w/cpp/numeric/valarray instead of std::vector ? They have interesting overloaded operators (but with the drawback of the C++ design for overloading operators where a local variable (created in the stack) is needed for storing the result before to be copied with the return keyword, so lot of overhead) and maybe you also loose the help of CUDA.

**Comment by martinjrobins** [comment]
Hi @Lecrapouille. I havn't tried a std::valarray, but from what I understand a valarray is non-resizeable? If so, then Aboria won't work directly with a valarray for the internal storage, as it assumes that there is a push_back method. Mind you, if valarray was useful for a certain use-case, then there would be no cost to wrap the memory pointed to by each std::vector in a valarray. For example, to use the default `id` variable as a valarray, you could do something like the following

`
Aboria::Particles<> particles(N);
std::valarray<size_t> id_array(Aboria::get<id>(particles).data());
\\ use id_array for something....
`

**Comment by Lecrapouille** [comment]
@martinjrobins sorry for not having replied you sooner ! std::valarray is resizeable with the resize() method but that invalidates old values (you have to re-insert them + the new ones). You have to do that manually, so this is a lot more painful than inserting with a std::vector which hides it for you (but std::vector probably copies old elements one by one) but here have the control on the reallocation size strategy (instead of *2 like std::vector does). http://cppisland.com/?p=518

Alternative:
https://github.com/facebook/folly/blob/master/folly/docs/FBVector.md

**Comment by martinjrobins** [comment]
Do you have a specific problem where you need a `std::valarray`? If so, as I mention above you will be able to wrap the `std::vector` returned by Aboria's `get` functions into a `std::valarray` easily enough. Let me know if you run into any problems.
