### ISSUE TITLE
Bug when Changing Particles Positions

### ISSUE THREAD

**Issue by JabirSS** [martinjrobins/Aboria#31]
Dear @martinjrobins , 

I am facing a strange bug.

I'm doing the following in my main file:

```         
 //create particles, symbols, etc...

v[a]+=0.5*dt*dvdt[a];
//write vtk
x[a] += 0.5 * dt * v[a];
//write vtk

```

The first VTK file created above seems fine, however, when examining the second file, I see that the values of dvdt in addition to several other variables have changed drastically ( up to +/- 1.0 e13)! As you can see nothing was done in between aside from shift the positions,  so I'm truly puzzled as to why that happened.
I have tried so many things to try and find out what is wrong, but no luck so far...
I'd greatly appreciate any ideas you might have!

**Comment by martinjrobins** [comment]
Hi @JabirSS. I can't see anything from the code you have provided, are you able to attach the full code to this issue?

One thing I can think off: when you change the positions, you change the order of the particles in the particle set, so the order in which they are written to the vtk will change (however their ids should stay the same), could that be the issue?

**Comment by JabirSS** [comment]
Dear @martinjrobins ,
Thanks for your quick reply, as always!
I don't think that's the issue here but I have sent  the source file to the email you mention on github.

**Comment by martinjrobins** [comment]
no worries, glad you got it sorted.
