### ISSUE TITLE
Variable Manipulation

### ISSUE THREAD

**Issue by JabirSS** [martinjrobins/Aboria#42]
Hello @martinjrobins,

Recently I found myself needing to do something like this:

```
//for some Aboria variable x:
x1=f(x);
x2=f1(c1*x1+c2*x);
x3=...
x=f3(a*x1+b*x2+c*x3...etc);

```
Now the straight-forward way to do it would be to declare additional aboria varialbes for x1, x2, etc., but I would like to avoid doing that, since the number of variables might be large and they are only temporary.
Another approach I tried was to access the x array data using `get<x>(particles)` and then assigning it to an `std::vector`, however, doing the kind of operations I need with `std::transform` might be troublesome. I have also looked into using `std::valarray` but I have concerns regarding performance.

I guess all approaches above are viable, but I was curious whether there's some other neater way within the framework of Aboria that allows me to do this that I might have missed?

Finally, I noticed that the vector cross operation is missing, I tried adding it to the Vector.h and Funtions.h but it was a bit tricky, so I just wrapped it as a lazy Aboria function..Do you think it would it be faster if I included it in the headers or is performance comparable, so I shouldn't bother?

Thanks!

**Comment by martinjrobins** [comment]
I assume you are using the symbolic api? You have a few options I think. You could write a lazy Aboria function (like the sph example) that calculated the result of `f3`, given `x`. Or you could write something like this:

```cpp
auto x1 =  f(x[i]);
auto x2 = f2(c1*x1+c2*x[i]);
x[i] = f3(a*x1+b*x2+...etc);
```
In the above, `x1` and `x2` are expressions, rather than values, and these expressions are only evaluated on the third line when you assign to `x[i]`. That way the compiler can work out all the temporaries for you. You are giving more work to the compiler though of course.

**Comment by martinjrobins** [comment]
with the cross operation, using a lazy function will  work fine with no performance penalty, so I would go with that if it works already.

**Comment by JabirSS** [comment]
Thanks for the quick reply, as always!

My problem with that approach is that I need to store multiple versions of
x as well during the process, and I found that using something  like auto
x1=x, then changing x would also change x1. Any way to store temporary
variables that can be used in the sembolic api without creating aboria
variables?

**Comment by martinjrobins** [comment]
Not sure I understand what you mean. Why do you need to store multiple versions of x, is it for your output? 

If you write:

```cpp
Symbol<x_variable> x;
Label<0, container_type> i(particles);
auto x1 = 2*x[i];
```
then `x1` will have a strange-looking type that encodes the expression 2*x[i], it won't actually be a value. You could then create another function that uses the x1 expression and assign this back to x via:

```cpp
x[i] = 4*x1;
```
Note that this is *exactly* the same as writing:

```cpp
x[i] = 4*(2*x[i]);
```

The other option is to create a lazy Aboria function:

```cpp
struct myfun {
  typedef double result_type;
  double operator()(const double x) const {
    const double x1_value = 2*x;
    return 4*x;
  }
};

ABORIA_UNARY_FUNCTION(F, myfun, SymbolicDomain);
```

**Comment by JabirSS** [comment]
Basically I need this for multi-stage integrators such as the runge-kutta, so for the example mentioned earlier:

```
auto x1 =  f(x[i]);
auto x2 = f2(c1*x1+c2*x[i]);
x[i] = f3(a*x1+b*x2+...etc);
```
f, f2 and f3 are actually pretty elaborate functions that can potentially have sub-routines involving both symbolic api expressions and regular loops, hence my preference for temporary variables to store intermediate steps that can then be used in symbolic api expressions.
